### ISSUE TITLE
enhancement: progressive operations

### ISSUE THREAD

**Issue by dan-cristian** [TurboGit/hubicfuse#97]
Hubicfuse is missing support for progressive download and upload. 
User has to wait for the whole file to be dowloaded before it can be accessed via fuse. 
Progress status on file copy is also incorrect as it shows progress relative to local cached file.
Would be great if progressive support can be added to hubicfuse.

**Comment by dan-cristian** [comment]
I have implemented a very basic progressive upload function in this branch: https://github.com/dan-cristian/hubicfuse/tree/progressive_operations
As a shortcoming after implementing the progressive upload, large segmented file support is not working, needs fixing.

**Comment by weekendowel** [comment]
I also think progressive downloads would be really useful. For example starting a video before it is fully downloaded

**Comment by mspeder** [comment]
I’ve been thinking about reworking the segment handling code in order to
- remove unnecessary upload of untouched segments
- only download segments when needed and cache them between access
Main benefits would be obviously reduced bandwidth and smaller local space consumption as well as improved access latency.
 
In order to achieve this, my current idea is described below.
As this would probably lead to significant changes, I would greatly appreciate the feedback from the community before investigating further !

1/ Use a fixed and low (10MB for instance, configurable anyway) segment size "S". Key point is that the use of hubic segments maintains compatibility.
2/ Maintain a pool of locally available segments (backed by separate local files). Each segment has a modified flag and also carry information about related file and segment number.
3/ Segments are added/downloaded to the pool when accessed (r/w)
4/ Segments are removed from the pool (uploaded at that time if modified) by oldest access time when the pool is growing above a certain, configurable, limit
5/ When a file is "closed", modified segments are forced to sync to hubic, but also kept locally (garbage collect being done by 4/)
6/ If an existing file is not "correctly split" (ie all its segments are not "S" sized, except the last one), it is globally re-uploaded to match this condition only when the first write to it occurs. This would help efficient transition from existing accounts not matching this format and this would only be required once per file.

**Comment by dan-cristian** [comment]
This sounds good. I have partially implemented the progressive download using segments, however I run into an unexpected issue, curl download speed is random, sometimes segments are being dowloaded very slow (~50Kbps) which makes realtime video playing not possible. Usually the first segments comes very fast (~5 MBps), then randomly speeds drops.

I could not figure it out a solution yet, have tried with latest libcurl from github, no luck.

**Comment by TurboGit** [comment]
I have no idea about the issue here. Maybe that's just expected for an hubic client. I mean there is no guarantee that the download be continuously at the same speed. Are you using a large buffer to cop with the variation of the download speed?

**Comment by dan-cristian** [comment]
I use a large buffer, fuse is launched with large_read and big_writes option and the segment is written directly on the disk, no intermediate memory buffer. It is odd that after 2-3 segments downloaded with a fast speed (3-5 MBps) it suddenly drops to under 100 KBps.
I am thinking I should try curl_multi interface instead of curl_easy.

**Comment by dan-cristian** [comment]
The issue seems to be not related to curl, but to hubic cloud storage. Hubic is throthling the download speed apparently random. A solution is to use larger size segments to have a large buffer, or to stop a slow download and retry, hoping download will work with a higher speed.

**Comment by TurboGit** [comment]
let's close this at this stage and let's reopen if some we have some more/better idea...
